<?php
/**
 * Returns the list of NTA codes that have mutual aid coverage.
 * Reads from a static JSON cache generated by cron/cacheupdate.php,
 * falling back to live Airtable API calls if the cache is missing.
 */

$cacheFile = __DIR__ . '/coverage_cache.json';

if (file_exists($cacheFile)) {
    header('content-type: application/json');
    readfile($cacheFile);
    exit;
}

// Fallback: live Airtable API (slow, ~6s)
include __DIR__ . '/../includes/init.php';
session_start();
$model = new AirtableCovidModel();
if (!isset($_SESSION['ntas']) || !$_SESSION['ntas']) {
    $_SESSION['ntas'] = $model->getNtaList();
}

if (!isset($_SESSION['coverage']) || !$_SESSION['coverage'] || !isset($_SESSION['coverage_ts']) || $_SESSION['coverage_ts'] <= time()) {
    $_SESSION['coverage'] = $model->getCoverage();
    $_SESSION['coverage_ts'] = time() + 600;
}

header('content-type: application/json');
echo json_encode(ntas());


function ntas()
{
    $rr = [];
    foreach ($_SESSION['ntas'] as $nta) {
        if (array_search($nta['id'], $_SESSION['coverage'])) {
            $rr[] = ['nta' => $nta['code']];
        }
    }
    return $rr;
}
