<?php
include __DIR__ . '/../includes/init.php';
session_start();

$model = new Model();

// Load NTA list from static cache (generated by cron) instead of live Airtable API
$ntaCacheFile = __DIR__ . '/nta_list_cache.json';
if (!isset($_SESSION['ntas']) || !$_SESSION['ntas']) {
    if (file_exists($ntaCacheFile)) {
        $_SESSION['ntas'] = json_decode(file_get_contents($ntaCacheFile), true);
    } else {
        // Fallback: live Airtable API (slow, ~3s)
        $_SESSION['ntas'] = AirtableCovidModel::getNtaList();
    }
}
$ntaName = mapIncomingRequest($_GET);

$cards = $ntaName ? $model->getCovidPrj($ntaName) : null;

header('content-type: text/html; charset=UTF-8');
//echo json_encode($cards);
echo "<!-- Debug: NTA='{$ntaName}' Count=" . count((array)$cards) . " -->";
echo "<span id='response-nta-name' style='display:none;'>{$ntaName}</span>";
viewResponse($cards);



function mapIncomingRequest($rr)
{
	if ((!isset($rr['nta']) || !$rr['nta']) && (!isset($rr['address']) || !$rr['address']))
		return null;
	if (isset($rr['nta']) && is_array($rr['nta']))
		$rr['nta'] = array_shift($rr['nta']);
	if (isset($rr['address']) && $rr['address'])
	{
		$gcNta = Geoclient::getNtaCode($rr['address']);
		if ($gcNta)
			$rr['nta'] = $gcNta;
	}	
	
	return $_SESSION['ntas'][$rr['nta']]['name'];
}


/// viewer ////////////////////////////////////////////////

function viewResponse($cc)
{
	if ($cc === null)
	{
		echo 'It is not possible to detect neighborhood zone by entered address. Please try again';
		die();
	}
	if (!$cc)
	{
		echo 'Sadly nothing found. Please try another neighbourhood zone';
		die();
	}
	?>
	<div>
	  <?php foreach ($cc as $c)
	  {
			viewGroup($c);
	  }
	  ?>
	</div>
	
	<?php
}


function viewGroup($gr)
{
	$vv = new grViewer($gr);
	$ii = $vv->images();
	#print_r($gr);
?>
	<div class="card mb-3">
		<div class="card-body">
			<?php if ($ii) : ?>
			  <?php $img = array_pop($ii); ?>
			  <div class="galleryIcons">
				<a href="<?php echo $img['url']; ?>" target="_blank">
					<img class="bigIcon" src="<?php echo $img['bigIcon']; ?>"/>
				</a>
				<?php if ($ii) : ?>
				  <div>
					<?php foreach($ii as $img) : ?>
						<a href="<?php echo $img['url']; ?>" target="_blank">
							<img class="smallIcon" src="<?php echo $img['icon']; ?>"/>
						</a>
					<?php endforeach; ?>
				  </div>
				<?php endif; ?>
			  </div>
			<?php endif; ?>
			<h5 class="title col-11 pl-0"><?php echo $vv->v('name'); ?></h5>
			<div class="project-desc mb-2"><?php echo nl2br($vv->v('description') ?? ''); ?></div>
			
			<p>
				<?php if (isset($vv->dd['txt:phones']) && $vv->dd['txt:phones']) : ?>
					<?php foreach ($vv->dd['txt:phones'] as $ph) : ?>
						<a title="<?php echo $ph; ?>" href="tel:<?php  echo $ph; ?>"><i data-feather="phone-outgoing"></i></a>
					<?php endforeach; ?>
				<?php endif; ?>
				<?php if (isset($vv->dd['email']) && $vv->dd['email']) : ?>
					<a title="<?php $vv->v('email'); ?>" href="mailto:<?php $vv->v('email'); ?>"><i data-feather="mail"></i></a>
				<?php endif; ?>
				<?php if (isset($vv->dd['website']) && $vv->dd['website']) : ?>
					<a title="<?php $vv->v('website'); ?>" href="<?php $vv->v('website'); ?>" target="_blank"><i data-feather="external-link"></i></a>
				<?php endif; ?>
				<?php if (isset($vv->dd['Facebook']) && $vv->dd['Facebook']) : ?>
					<a title="<?php echo $vv->dd['Facebook']; ?>" href="<?php $vv->v('Facebook'); ?>" target="_blank"><i data-feather="facebook"></i></a>
				<?php endif; ?>
				<?php if (isset($vv->dd['Instagram']) && $vv->dd['Instagram']) : ?>
					<a title="<?php echo $vv->dd['Instagram']; ?>" href="<?php $vv->v('Instagram'); ?>" target="_blank"><i data-feather="instagram"></i></a>
				<?php endif; ?>
				<?php if (isset($vv->dd['X']) && $vv->dd['X']) : ?>
					<a title="<?php echo $vv->dd['X']; ?>" href="<?php $vv->v('X'); ?>" target="_blank"><i data-feather="twitter"></i></a>
				<?php endif; ?>
				
				<div class="ml-0 mt-1"><i data-feather="map-pin"></i>
					<small>
						<?php echo implode(' | ', $vv->ntas()); ?>
					</small>
				</div>
			</p>
			
			<div class="modalPills">
				<?php foreach(mapTypes($vv->dd['Geographical Scope']) as $type => $style) : ?>
					<span class="badge badge-pill" <?php echo $style; ?>><?php echo $type; ?></span>
				<?php endforeach; ?>
			</div>
			
		</div>
	</div>
<?php
}

function mapTypes($tt)
{
	$idx = [
		'Global' => 'style="background-color: #550D00; color: #EEEEEE;"',
		'National' => 'style="background-color: #4E9C68; color: #EEEEEE;"',
		'New York City' => 'style="background-color: #022835; color: #EEEEEE;"', 
		'New York State' => 'style="background-color: #003E15; color: #EEEEEE;"',
		'Bronx' => 'style="background-color: #802615; color: #EEEEEE;"',
		'Brooklyn' => 'style="background-color: #804C15; color: #EEEEEE;"',
		'Queens' => 'style="background-color: #104050; color: #EEEEEE;"',
		'Manhattan' => 'style="background-color: #105D2A; color: #EEEEEE;"',
		'Staten Island' => 'style="background-color: #FFB7AA; color: #550D00;"',
		'Long Island' => 'style="background-color: #FFD6AA; color: #552C00;"',
		'New Jersey' => 'style="background-color: #7CA3AF; color: #022835;"',
		/*
		'food' => 'style="background-color: #9CDBB2; color: #003E15;"',
		'advocacy' => 'style="background-color: #D47B6A; color: #000000;"',
		'housing' => 'style="background-color: #D4A16A; color: #000000;"',
		'mental health' => 'style="background-color: #6595B5; color: #000000;"',
		'information' => 'style="background-color: #4E9C68; color: #000000;"',
		'digital access' => 'style="background-color: #3F002E; color: #EEEEEE;"',
		'delivery/transport' => 'style="background-color: #5F1049; color: #EEEEEE;"',
		'Medical' => 'style="background-color: #BE7FAD; color: #3F002E;"'
		*/
	];
	$rr = [];
	foreach ((array)$tt as $t)
		$rr[$t] = $idx[$t];
	return $rr;
}


class grViewer
{
	var $dd;
	function __construct($gr)
	{
		$this->dd = $gr;
		// DB fields are already flattened, but some might be JSON encoded.
		// For simplicity, we might need to assume fields are available directly.
		// However, the original code looked for 'Group Name' etc. which are Airtable keys.
		// In database, we probably saved them as 'Group Name' etc?
		// Wait, cacheupdate.php used normRec(['id' => $aCard['id']] + $aCard['fields'], 'covid_prj');
		// And normRec uses specific keys like 'name', 'description'.
		// So $gr will have 'name', 'description' etc directly.
		
		// Map DB columns back to what grViewer expects or update grViewer.
		// Let's update grViewer usage.
		$this->dd['Group Name'] = $this->dd['name'];
		$this->dd['Short Description'] = $this->dd['description'];
		$this->dd['Group Email'] = $this->dd['email_pub'] ?? ''; // cacheupdate maps email_pub
		$this->dd['Website'] = $this->dd['url'];
		
		// Remap for compatibility
		$this->dd['name'] = $this->dd['Group Name'] ?? '';
		$this->dd['description'] = $this->dd['Short Description'] ?? '';
		$this->dd['email'] = $this->dd['Group Email'] ?? '';
		$this->dd['website'] = $this->dd['website'] ?? '';
		$this->dd['Facebook'] = $this->dd['facebook'] ?? null;
		$this->dd['Instagram'] = $this->dd['instagram'] ?? null;
		$this->dd['X'] = $this->dd['twitter'] ?? null;

		if (isset($this->dd['geo_scope']) && is_string($this->dd['geo_scope'])) {
			$this->dd['Geographical Scope'] = json_decode($this->dd['geo_scope'], true);
		} else {
			$this->dd['Geographical Scope'] = $this->dd['Geographical Scope'] ?? [];
		}

		if (isset($this->dd['nta']) && is_string($this->dd['nta'])) {
			$this->dd['Neighborhoods'] = json_decode($this->dd['nta'], true);
		} else {
			$this->dd['Neighborhoods'] = $this->dd['Neighborhoods'] ?? [];
		}

		if (isset($this->dd['images']) && is_string($this->dd['images'])) {
			$this->dd['Cover Image'] = json_decode($this->dd['images'], true);
		} else {
			$this->dd['Cover Image'] = $this->dd['Cover Image'] ?? [];
		}
	}
	
	function v($f)
	{
		$d = $this->dd[$f] ?? '';
		switch ($f)
		{
			case 'Facebook':
				$d = str_replace('@', 'https://www.facebook.com/', $d);
				break;
			case 'Instagram':
				$d = str_replace('@', 'https://www.instagram.com/', $d);
				break;
			case 'X':
				$d = str_replace('@', 'https://twitter.com/', $d);
				break;
			case 'website':
				$d = preg_match('~http~si', $d) ? $d : "//{$d}";
				break;
		}
		echo $d;
	}
	
	function images()
	{
		$rr = [];
		foreach ((array)($this->dd['Cover Image'] ?? []) as $i)
			$rr[] = ['url' => $i['url'], 'icon' => $i['thumbnails']['small']['url'], 'bigIcon' => $i['thumbnails']['large']['url']];
		return $rr;
	}
	
	function ntas()
	{
		return (array)$this->dd['Neighborhoods'];
	}
}